input's info tooltips added by passing shinypanels' infoTooltip funct…
datasketch/parmesan pull request #39
Opened 2020-05-20 00:43 UTC by brazadas

…ion to label argument in every widget; also test added closes #26

2020-05-20 20:59 UTC, jpmarindiaz commented
Tests passing... OK.
But the app in EX01, doesn't work for me, any ideas?

![image](https://user-images.githubusercontent.com/1489570/82496743-d1076380-9ab2-11ea-8d3a-8ffd9ec63fb6.png)

2020-05-20 21:00 UTC, jpmarindiaz commented on inst/examples/ex01-basic/app.R
> +styles <- "
Please include all styles directly in the package

2020-05-20 21:07 UTC, jpmarindiaz requested changes
Fix comments and submit again. Example 01 should work even with shinypanels not loaded. Either import the shinypanels::infoTooltip function in the docs or duplicate it locally in this package.
Do not pollute example code with unnecesary CSS styles. If they are needed, they should go inside the package.

2020-05-20 21:07 UTC, jpmarindiaz commented on inst/examples/ex01-basic/app.R
> +  parmesan <- parmesan_load("parmesan")
No need to remove how we load files in all examples. Use devtools::load_all of crtl + shift + L to test locally

2020-05-20 21:07 UTC, jpmarindiaz commented on inst/examples/ex01-basic/parmesan/inputs.yaml
> +    icon:
do not leave blank, even when you are providing a default when NULL users will use the examples to learn how to change it. Use icon: info-circle

2020-05-20 21:07 UTC, jpmarindiaz commented on inst/examples/ex01-basic/parmesan/inputs.yaml
> +    text: fjsdksjdkskds
Use informative texts for all examples

2020-05-21 17:23 UTC, brazadas commented
Listo!

2020-05-21 17:31 UTC, merged